version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_volume:/var/lib/mariadb
    env_file:
      - .env
    expose:
      - "3306"
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file:
      - .env
    restart: on-failure
    expose:
      - "9000"
    networks:
      - my-network
    depends_on:
      - mariadb

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress_volume:/var/www/wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    restart: on-failure
    networks:
      - my-network
    depends_on:
      - wordpress

networks:
  my-network:
    name: my-network
    driver: bridge
# o: option de montage pour monter de ssysteme de fichier locaux(sur machine hôte)
# driver opts options suplementaire pour volume ici pour partage de fichier
volumes:
  wordpress_volume:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      device: /home/msainton/data/wordpress
      o: bind
  mariadb_volume:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      device: /home/msainton/data/mariadb
      o: bind